import type { Metadata } from "next";
import { DM_Sans, Inter } from "next/font/google";
import "./globals.css";
import { PrismaClient } from '@prisma/client';
import  ThemeProvider  from "@/lib/provider/next-theme-provider";
import { twMerge } from "tailwind-merge";
import { Session } from "@/lib/provider/session-provider";
import { SocketProvider } from "@/lib/provider/socket-provider";
import { CentralStorage } from "@/lib/provider/Central_Storage_Provider";


const inter = DM_Sans({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Kladbase",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {

  return (
    <html lang="en">
      <body className={twMerge('bg-background',inter.className)}>
       <Session>
        <CentralStorage>
       <ThemeProvider attribute="class" defaultTheme="dark" enableSystem>
        <SocketProvider>
        {children}
        </SocketProvider>
        </ThemeProvider> 
        </CentralStorage>
        </Session></body>
    </html>
  );
}
